// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 22.11.2025, 23:31:11
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/ingo/projects/hikeathon-2025/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ingo/projects/hikeathon-2025/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ingo/projects/hikeathon-2025/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ingo/projects/hikeathon-2025/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ingo/projects/hikeathon-2025/plugins/**/*.{js,ts,mjs}","/Users/ingo/projects/hikeathon-2025/composables/**/*.{js,ts,mjs}","/Users/ingo/projects/hikeathon-2025/utils/**/*.{js,ts,mjs}","/Users/ingo/projects/hikeathon-2025/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ingo/projects/hikeathon-2025/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ingo/projects/hikeathon-2025/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ingo/projects/hikeathon-2025/app.config.{js,ts,mjs}","/Users/ingo/projects/hikeathon-2025/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;